version: 2
jobs:
   build:
     docker:
       - image: aergus/latex
     steps:
       - checkout
       - run:
           name: Compile
           command: pdflatex main.tex
       - run:
           name: Generate output folder
           command: |
             mkdir /pdf;
             cp main.pdf /pdf/main.pdf;
       - store_artifacts:
           path: /pdf
